name: Combined Workflow

on:
  push:
    branches:
      - main  # or your default branch name

jobs:
  push-job:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run push-triggered tasks
        run: |
          current_branch=$(git branch --show-current)
          echo "Running push-triggered tasks on $current_branch"
          date
          # Your push-triggered tasks here

