name: Hello World GitHub Actions
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Hello world action and display merged branches
      run: |
        current_branch=${GITHUB_REF#refs/heads/}
        echo "Current branch: $current_branch"
        
        LAST_COMMIT_SHA=$(git log -n 1 --pretty=format:"%H")
        MERGE_COMMIT_SHA=$(git log --merges -n 1 --pretty=format:"%H")
        
        if [[ $LAST_COMMIT_SHA == $MERGE_COMMIT_SHA ]]; then
          # マージコミットの親コミットを取得
          PARENT_COMMITS=$(git show -s --pretty=%P $MERGE_COMMIT_SHA)
          PARENT2=$(echo $PARENT_COMMITS | awk '{print $2}')

          echo git branch -r --contains $PARENT2
          git branch -r --contains $PARENT2
          PARENT2_BRANCHES=($(git branch -r --contains $PARENT2 | sed 's/origin\///'))
          MERGED_BRANCH=""
          for branch in "${PARENT2_BRANCHES[@]}"; do
            if [[ $branch != $current_branch ]]; then
              MERGED_BRANCH=$branch
              break
            fi
          done
          echo "Merged branch: $MERGED_BRANCH"
        fi

