name: Hello World GitHub Actions
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Hello world action
      run: |
        echo "Hello, World!"
        merge_commit=$(git log --merges --pretty=format:"%H" -n 1)
        git rev-list --parents $merge_commit

