name: Hello World GitHub Actions
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Hello world action
      run: |
        echo "Hello, World!"
        merge_commit
        MERGE_COMMIT_SHA=$(git log --merges --pretty=format:"%H" -n 1)
        PARENT_COMMITS=$(git show -s --pretty=%P $MERGE_COMMIT_SHA)
        PARENT2=$(echo $PARENT_COMMITS | awk '{print $2}')
        git branch --contains $PARENT2 | grep -v "HEAD" | head -n 1 | awk '{print $NF}'

