name: Hello World GitHub Actions
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Hello world action
      uses: actions/checkout@v2
      run: |
        echo "Hello, World!"
        git rev-list --parents merge_commit

