name: Main Branch Workflow
on:
  push:
    branches:
      - main

jobs:
  main-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run main branch actions
        run: |
          echo "Running main branch actions"
          sleep 10
          date

