name: Combined Workflow

on:
  push:
    branches:
      - main  # or your default branch name
  pull_request:
    types: [closed]

jobs:
  push-job:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run push-triggered tasks
        run: |
          date
          # Your push-triggered tasks here

  pr-close-job:
    needs: push-job
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run PR close tasks
        run: |
          date
          # Your PR close tasks here

