name: Main Branch Action
on:
  repository_dispatch:
    types: [main_branch_action_triggered]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Main Branch - Awaited Build
      run: |
        echo "Running build on main branch after hoge branch completed"
