name: Hoge Branch Action
on: 
  push:
    branches:
      - hoge

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Hoge Branch - Build
      run: |
        echo "Running build on hoge branch"

    - name: Dispatch custom event for main branch
      if: success()
      run: |
        curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
        -H "Accept: application/vnd.github.v3+json" \
        https://api.github.com/repos/${{ github.repository }}/dispatches \
        -d '{"event_type":"main_branch_action_triggered", "client_payload": {"branch": "main"}}'

